# Generated by Django 5.1.2 on 2025-01-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_alter_rating_recipe'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rating',
            table='comments',
        ),
    ]
