# Generated by Django 5.1.2 on 2025-01-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipe',
            table='recipes',
        ),
    ]
